name: 'ESLint'
description: 'Lints JavaScript/TypeScript code.'
inputs:
  job-name:
    description: 'Optional name of the annotation author.'
  lint-all:
    description: 'Lint all files.'
runs:
  using: 'node12'
  main: 'dist/index.js'
